name: Build and Publish Chrome Extension

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Build extension
        run: |
          npm run build
          npm  run build:zip
      - name: Publish extension to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish'
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN_SECRET }}
          extension_id: ${{ secrets.CHROME_EXTENSION_ID }}
          zip_file: 'rami-levy-chrome-ext.zip'
